// <auto-generated />
namespace ItalieNieuw.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ItalieMigratie4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ItalieMigratie4));
        
        string IMigrationMetadata.Id
        {
            get { return "201403252001386_ItalieMigratie4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
