// <auto-generated />
namespace ItalieNieuw.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ItalieMigratie3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ItalieMigratie3));
        
        string IMigrationMetadata.Id
        {
            get { return "201403251816301_ItalieMigratie3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
