'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Beheren

    '''<summary>
    '''DagverslagenBeheer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DagverslagenBeheer As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''FotosBeheer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FotosBeheer As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''GastenboekBeheer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents GastenboekBeheer As Global.System.Web.UI.HtmlControls.HtmlAnchor
End Class
