'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Dagverslagen

    '''<summary>
    '''SqlNieuws control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlNieuws As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dgvOverzicht control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgvOverzicht As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''frvDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frvDetail As Global.System.Web.UI.WebControls.FormView

    '''<summary>
    '''dtsOverzicht control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtsOverzicht As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dtsDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dtsDetail As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''lblnaamnieuwtje control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblnaamnieuwtje As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtNaam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNaam As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Kalender1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Kalender1 As Global.System.Web.UI.WebControls.Calendar

    '''<summary>
    '''txtDatum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDatum As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtNieuws control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNieuws As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnToevoegen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnToevoegen As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAnnuleren control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAnnuleren As Global.System.Web.UI.WebControls.Button
End Class
