'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FotosBeheren

    '''<summary>
    '''fotogrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fotogrid As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''DtsOverzicht control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DtsOverzicht As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''btnMultipleRowDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMultipleRowDelete As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblLijstServerFotos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLijstServerFotos As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lsbBestandenOpServer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lsbBestandenOpServer As Global.System.Web.UI.WebControls.ListBox
End Class
